---
stack_env: ci-ceph-redhat
openstack_install_method: 'distro'
openstack_distro_type: 'osp'
undercloud_cidr:
  - cidr: 192.168.0.0/22
ceph:
  monitor_interface: eth0
  enabled: True
glance:
  store_ceph: True
primary_interface: ansible_eth0

state_path_base: /opt/stack/data

validate_certs: false

rhn_subscription:
  username: "{{ rhn_user }}"
  password: "{{ rhn_pass }}"

etc_hosts:
  - name: "{{ fqdn }}"
    ip: "{{ floating_ip }}"

neutron:
  enable_external_interface: True
  lbaas:
    enabled: False

common:
  hwraid:
    enabled: False

logging:
  enabled: true
  follow:
    enabled: true
    global_fields:
      customer_id: "unknown"
      cluster_name: "unknown"
    logs:
      - paths:
          - /var/log/messages
        fields:
          type: syslog
  forward:
    host: 127.0.0.1
    port: 4560

serverspec:
  enabled: false

xtradb:
  galera_version: 3
  client_version: 56
  server_version: 56

haproxy:
  stats_group: root

keystone:
  uwsgi:
    method: port

nova:
  libvirt_type: kvm

heat:
  enabled: True
  plugin_dirs:
    - '/usr/lib/heat'
    - '/usr/lib64/heat'

ironic:
  enabled: False

cinder:
  enabled: True
