---
project_name: cinder
cinder:
  services:
    cinder_api: "{{ openstack_meta.cinder.services.cinder_api[ursula_os] }}"
    cinder_scheduler: "{{ openstack_meta.cinder.services.cinder_scheduler[ursula_os] }}"
    cinder_volume: "{{ openstack_meta.cinder.services.cinder_volume[ursula_os] }}"
    cinder_backup: "{{ openstack_meta.cinder.services.cinder_backup[ursula_os] }}"
  enabled: True
  enabled_backends: [] # determined automatically by Ceph roles
  default_backend:
  backends: []
    # determined automatically by Ceph roles
  api_workers: 5
  state_path: "{{ state_path_base }}/cinder"
  volume_type: file
  volume_group: cinder-volumes
  create_vg: False
  common_volume_name: True
  allow_availability_zone_fallback: True
  data_pkgs:
    ubuntu:
      - cryptsetup
      - lvm2
      - tgt
      - nbd-client
      - open-iscsi
      - qemu-utils
    #FIXME do we need these pkgs on rhel?
    rhel:
      - cryptsetup
      - lvm2
      - targetcli
      - nbd
      - iscsi-initiator-utils
      - qemu-kvm-tools
  iscsi_helper:
    ubuntu: tgtadm
    rhel: targetcli
  tgt_service:
    ubuntu: tgt
    rhel: target
  iscsi_service:
    ubuntu: open-iscsi
    rhel: iscsid
  alternatives:
      - cinder-all
      - cinder-api
      - cinder-backup
      - cinder-manage
      - cinder-rootwrap
      - cinder-rtstool
      - cinder-scheduler
      - cinder-volume
      - cinder-volume-usage-audit
  heartbeat_timeout_threshold: 30
  distro:
    project_packages:
      - openstack-selinux
      - openstack-cinder
  source:
    rev: 'stable/newton'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/newton/upper-constraints.txt'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached }
    system_dependencies:
      ubuntu: []
      rhel: []
  logs:
  - paths:
      - /var/log/cinder/cinder-api.log
    fields:
      type: openstack
      tags: cinder,cinder-api
  - paths:
      - /var/log/cinder/cinder-manage.log
    fields:
      type: openstack
      tags: cinder,cinder-manage
  - paths:
      - /var/log/cinder/cinder-scheduler.log
    fields:
      type: openstack
      tags: cinder,cinder-scheduler
  - paths:
      - /var/log/cinder/cinder-volume.log
    fields:
      type: openstack
      tags: cinder,cinder-volume
  - paths:
      - /var/log/upstart/tgt.log
    fields:
      type: openstack
      tags: cinder,tgt
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile }}"
  monitoring:
    sensu_checks:
      check_cinder_services:
        criticality: 'critical'
  auditing:
    enabled: False
    logging: False
