---
- name: Install ceph-common
  apt: pkg={{ item }}
  with_items:
    - ceph-common={{ ceph.ceph_cloud_archive_version }}
  register: result
  until: result|succeeded
  retries: 5
  notify: restart glance services

- name: import rados module into glance
  file:
    src: /usr/lib/python2.7/dist-packages/{{ item }}
    dest: /opt/openstack/current/glance/lib/python2.7/site-packages/{{ item }}
    state: link
    owner: root
    group: root
    mode: 0644
  with_items:
    - rados.x86_64-linux-gnu.so
    - rbd.x86_64-linux-gnu.so

- name: remove modules those were used for Hammer
  file:
    path: /opt/openstack/current/glance/lib/python2.7/site-packages/{{ item }}
    state: absent
  with_items:
    - rados.py
    - rados.pyc
    - rbd.py
    - rbd.pyc
    - rados.so
    - rbd.so

- name: fetch glance keyring
  slurp: path=/etc/ceph/ceph.client.glance.keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: glance_keyring

- name: write glance keyring
  copy:
    dest: "{{ glance_keyring['source'] }}"
    content: "{{ glance_keyring['content'] | b64decode }}"
    mode: 0644
    owner: glance
    group: glance
