---
redhat:
  poolids:
    - 8a85f98158880f8d01588bde0f7c3c43
  repos:
    - rhel-7-server-extras-rpms
    - rhel-7-server-openstack-10-rpms
    - rhel-7-server-rh-common-rpms
    - rhel-7-server-openstack-10-tools-rpms
    - rhel-7-server-openstack-10-optools-rpms
    - rhel-7-server-openstack-10-tools-debug-rpms
    - rhel-7-server-rhceph-2-mon-rpms
    - rhel-7-server-rhceph-2-tools-rpms
    - rhel-7-server-optional-rpms
