---
install_inspec_controls: []

inspec:
  version: ~
  enabled: true
  interval: 43200
  dependency_install_method: 'tar'
  dependency_path: /etc/inspec/
  profiles:
    openstack_security:
      name: inspec-openstack-security
      version: master
      url: https://github.com/chef-partners/inspec-openstack-security/archive/master.tar.gz
    stig_rhel:
      name: inspec-stig-rhel7
      version: master
      url: https://github.com/inspec-stigs/inspec-stig-rhel7/archive/master.tar.gz
    ursula-inspec:
      name: ursula-inspec
      version: master
      url: https://github.com/blueboxgroup/ursula-inspec/archive/master.tar.gz
  controls:
    rhel7:
      enabled: true
      profile: stig_rhel
      skip_controls: []
      attributes:
        RHEL_07_030710_audit_key_name: audit_account_changes-V-38531
        client_alive_interval: '900'
        RHEL_07_030523_audit_key_name: actions-V-38578
    horizon:
      enabled: true
      profile: openstack_security
      attributes:
        horizon_config_group: apache
      required_controls:
        - check-dashboard-01
        - check-dashboard-02
        - check-dashboard-03
        - check-dashboard-04
        - check-dashboard-05
        - check-dashboard-06
        - check-dashboard-07
        - check-dashboard-08
        - check-dashboard-09
        - check-dashboard-10
        - check-dashboard-11
    cinder:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-block-01
        - check-block-02
        - check-block-03
        - check-block-04
        - check-block-05
        - check-block-06
        - check-block-07
        - check-block-08
    glance:
      enabled: true
      profile: openstack_security
      attributes:
        glance_config_files:
          - glance_api_audit_map.conf
          - glance-api-paste.ini
          - glance-api.conf
          - glance-cache.conf
          - glance-glare.conf
          - glance-registry-paste.ini
          - glance-registry.conf
          - glance-scrubber.conf
          - glance-swift-store.conf
          - policy.json
          - schema-image.json
      required_controls:
        - check-image-01
        - check-image-02
        - check-image-03
        - check-image-04
    nova_data:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-compute-01
        - check-compute-02
        - check-compute-03
        - check-compute-04
        - check-compute-05
    nova_control:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-compute-01
        - check-compute-02
        - check-compute-03
        - check-compute-04
    keystone:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-identity-01
        - check-identity-02
        - check-identity-03
        - check-identity-04
        - check-identity-05
        - check-identity-06
    neutron_data:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-neutron-01
        - check-neutron-02
        - check-neutron-03
        - check-neutron-04
    neutron_control:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-neutron-01
        - check-neutron-02
        - check-neutron-03
        - check-neutron-04
        - check-neutron-05
    heat:
      enabled: true
      attributes:
        heat_enabled: true
      profile: openstack_security
      required_controls:
        - check-orchestration-01
        - check-orchestration-02
        - check-orchestration-03
    ceilometer:
      enabled: true
      profile: openstack_security
      attributes:
        ceilometer_enabled: true
      required_controls:
        - check-telemetry-01
        - check-telemetry-02
        - check-telemetry-03
        - check-telemetry-04
    aodh:
      enabled: true
      profile: openstack_security
      attributes:
        aodh_enabled: true
      required_controls:
        - check-telemetry-alarming-01
        - check-telemetry-alarming-02
        - check-telemetry-alarming-03
    kvm:
      enabled: true
      profile: ursula-inspec
      required_controls:
        - KVM001
        - KVM002
        - KVM003
        - KVM004
    mongodb:
      enabled: true
      profile: ursula-inspec
      required_controls:
        - MON001
        - MON002
        - MON003
        - MON004
        - MON005
        - MON006
        - MON007
        - MON008
    mysql:
      enabled: true
      profile: ursula-inspec
      required_controls:
        - MYSQL001
        - MYSQL002
        - MYSQL003
        - MYSQL004
        - MYSQL005
        - MYSQL006
    rabbitmq:
      enabled: true
      profile: ursula-inspec
      required_controls:
        - RABBITMQ001
        - RABBITMQ002
        - RABBITMQ003
        - RABBITMQ004
        - RABBITMQ005
        - RABBITMQ006
        - RABBITMQ007
