---
install_inspec_controls: []

inspec:
  version: ~
  enabled: true
  interval: 43200
  dependency_install_method: 'tar'
  dependency_path: /etc/inspec/
  profiles:
    openstack_security:
      name: inspec-openstack-security
      version: master
      url: https://github.com/chef-partners/inspec-openstack-security/archive/master.tar.gz
    stig_rhel:
      name: inspec-stig-rhel7
      version: master
      url: https://github.com/inspec-stigs/inspec-stig-rhel7/archive/master.tar.gz
  controls:
    rhel7:
      enabled: true
      profile: stig_rhel
      skip_controls: []
      attributes:
        RHEL_07_030710_audit_key_name: audit_account_changes-V-38531
        client_alive_interval: '900'
        RHEL_07_030523_audit_key_name: actions-V-38578
    horizon:
      enabled: true
      profile: openstack_security
      attributes:
        horizon_config_group: apache
      required_controls:
        - check-dashboard-01
        - check-dashboard-02
        - check-dashboard-03
        - check-dashboard-04
        - check-dashboard-05
        - check-dashboard-06
        - check-dashboard-07
        - check-dashboard-08
        - check-dashboard-09
        - check-dashboard-10
        - check-dashboard-11
    cinder:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-block-01
        - check-block-02
        - check-block-03
        - check-block-04
        - check-block-05
        - check-block-06
        - check-block-07
        - check-block-08
    glance:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-image-03
        - check-image-04
    nova:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-compute-01
        - check-compute-02
        - check-compute-03
        - check-compute-04
    keystone:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-identity-01
        - check-identity-02
        - check-identity-03
        - check-identity-04
        - check-identity-05
        - check-identity-06
    neutron:
      enabled: true
      profile: openstack_security
      required_controls:
        - check-neutron-01
        - check-neutron-02
        - check-neutron-03
        - check-neutron-04
