---
client:
  write_stackrc: True
  self_signed_cert: false
  names:
    - python-keystoneclient
    - python-glanceclient
    - python-novaclient
    - python-neutronclient
    - python-cinderclient
    - python-heatclient
    - python-ceilometerclient
    - python-ironicclient
    - python-swiftclient
    - python-magnumclient
    - python-openstackclient
  apt_packages:
    - python-prettytable
