---
client:
  self_signed_cert: false
  names:
    - oslo.utils==3.2.0
    - python-keystoneclient<3.0.0
    - python-glanceclient>=1.1.0
    - python-novaclient<3.0.0
    - python-neutronclient<2.27.0
    - python-cinderclient
    - python-heatclient==0.8.1
    - python-ironicclient==1.0.0
    - python-swiftclient
