---
- name: install docker
  apt: pkg=docker-engine

- name: add users to docker group
  user: name={{ item }} groups=docker append=yes
  with_items: docker.allow

- name: install docker python client
  pip: name=docker-py

- name: configure docker service
  template: src=etc/default/docker dest=/etc/default/docker
  notify: restart docker service

- meta: flush_handlers

- name: make sure docker is running
  service: name=docker state=started
