---
- name: Add flavors
  os_nova_flavor:
    name: '{{ item.name }}'
    ram: '{{ item.ram | int }}'
    disk: '{{ item.disk | int }}'
    vcpus: '{{ item.vcpus | int }}'
    flavorid: '{{ item.flavorid | default(omit) }}'
    rxtx_factor: '{{ item.rxtx_factor | default(omit) }}'
    ephemeral: '{{ item.ephemeral | default(omit) }}'
    is_public: '{{ item.is_public | default(omit) }}'
    swap: '{{ item.swap | default(omit) }}'
    validate_certs: "{{ validate_certs|default(omit) }}"
    state: present
    auth:
      auth_url: "{{ endpoints.auth_uri  }}"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password  }}"
  with_items: '{{ nova.flavors | default([]) }}'
  run_once: true
  # FIXME flavors are always added, even if it's just an Ironic cloud

- name: Add ironic flavors
  os_nova_flavor:
    name: '{{ item.name }}'
    ram: '{{ item.ram | int }}'
    disk: '{{ item.disk | int }}'
    vcpus: '{{ item.vcpus | int }}'
    flavorid: '{{ item.flavorid | default(omit) }}'
    rxtx_factor: '{{ item.rxtx_factor | default(omit) }}'
    ephemeral: '{{ item.ephemeral | default(omit) }}'
    is_public: '{{ item.is_public | default(omit) }}'
    swap: '{{ item.swap | default(omit) }}'
    state: present
    validate_certs: "{{ validate_certs|default(omit) }}"
    auth:
      auth_url: "{{ endpoints.auth_uri  }}"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password  }}"
  with_items: '{{ ironic.flavors | default([]) }}'
  when: ironic.enabled | default(False) | bool
