---
- name: install memcached packages
  package: name=memcached
  register: result
  until: result|succeeded
  retries: 5

- name: install memcached packages
  package:
    name=libsasl2-dev
  when: os == 'ubuntu'
  register: result
  until: result|succeeded
  retries: 5

- name: install memcached packages
  package:
    name=cyrus-sasl-devel
  when: os == 'rhel'
  register: result
  until: result|succeeded
  retries: 5


- name: install memcached packages
  package:
    name=python-memcache
  when: os == 'ubuntu'
  register: result
  until: result|succeeded
  retries: 5

- name: install memcached packages
  package:
    name=python-memcached
  when: os == 'rhel'
  register: result
  until: result|succeeded
  retries: 5

- name: "remove /nonexistent inadvertently created by memcached package: see https://bugs.launchpad.net/ubuntu/+source/memcached/+bug/1255328/"
  file: dest=/nonexistent state=absent

- name: memcached configuration
  template: src=memcached.conf dest=/etc/memcached.conf mode=0644
  notify:
    - restart memcached

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
